export PATH=/opt/homebrew/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/aj/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="aj"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  asdf
  docker
  git
  git-prompt
  npm
  postgres
  tmux
  vscode
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#
# Aliases
#

# Repeat the previous command with `sudo`.
alias please='sudo $(fc -n -l -1)'

# Prompt before overwriting things, and list changes.
alias cp='cp -iv'
alias mv='mv -iv'

# Provide several variations of `ls`.
alias l='ls'
alias la='ls -a'
alias ll='ls -l'

# Create intermediate directories and list changes.
alias mkdir='mkdir -pv'

# Send files to the macOS trash can.
trash () { command mv "$@" ~/.Trash ; }

# Launch tmux with all colors
alias tmux='tmux -2'


#
# Docker
#

alias de='docker exec -it'


#
# Elixir
#

export ERL_AFLAGS="-kernel shell_history enabled"
export KERL_BUILD_DOCS="yes"


#
# Git
#

# Convenient aliases.
alias g='git status'
alias gc='git commit --verbose'
alias gd='git diff'
alias gs='git switch'
alias gap='git add -p'
alias gco='git checkout'

# Allow easy add of the current directory.
unalias ga
ga () {
  if [ -z $1 ]
  then
    git add .
  else
    git add $@
  fi
}

# Completions
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash


#
# Golang
#

export GOPATH=$HOME/.go
#export GOROOT=/usr/local/go
export PATH=$PATH:$GOPATH/bin


#
# PostgreSQL
#

export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin


#
# Shell
#

# Prevent cross-terminal history sharing
unsetopt inc_append_history
unsetopt share_history


#
# Terraform
#

if [ -f /usr/local/bin/terraform ]
then
  complete -o nospace -C /usr/local/bin/terraform terraform
fi


#
# Local Tweaks
#

source ~/.zshrc_local


#
# Finalize
#

fpath=(~/.zsh $fpath)
autoload -Uz compinit && compinit
