export PATH=/opt/homebrew/bin:/Users/aj/.files/bin:$PATH
export ZSH="/Users/aj/.oh-my-zsh"

ZSH_THEME="aj"

plugins=(
  asdf
  docker
  git
  git-prompt
  npm
  postgres
  tmux
  vscode
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

#
# Aliases
#

# Export .env files
exenv () { export $(cat .env | xargs) }

# Fix missing Python in macOS 12.3
alias python='python3'

# Repeat the previous command with `sudo`.
alias please='sudo $(fc -n -l -1)'

# Prompt before overwriting things, and list changes.
alias cp='cp -iv'
alias mv='mv -iv'

# Provide several variations of `ls`.
alias l='ls'
alias la='ls -a'
alias ll='ls -l'

# Create intermediate directories and list changes.
alias mkdir='mkdir -pv'

# Send files to the macOS trash can.
trash () { command mv "$@" ~/.Trash ; }

# Launch tmux with all colors
alias tmux='tmux -2'


#
# Docker
#

alias de='docker exec -it'


#
# Elixir
#

export ERL_AFLAGS="-kernel shell_history enabled"
export KERL_BUILD_DOCS="yes"


#
# Git
#

# Convenient aliases.
alias g='git status'
alias gc='git commit --verbose'
alias gd='git diff'
alias gs='git switch'
alias gap='git add -p'
alias gco='git checkout'
alias gpf='git push --force-with-lease'

# Allow easy add of the current directory.
unalias ga
ga () {
  if [ -z $1 ]
  then
    git add .
  else
    git add $@
  fi
}

# Completions
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash


#
# Golang
#

export GOPATH=$HOME/.go
#export GOROOT=/usr/local/go
export PATH=$PATH:$GOPATH/bin


#
# PostgreSQL
#

export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin


#
# Shell
#

# Prevent cross-terminal history sharing
unsetopt inc_append_history
unsetopt share_history


#
# Terraform
#

if [ -f /usr/local/bin/terraform ]
then
  complete -o nospace -C /usr/local/bin/terraform terraform
fi


#
# Local Tweaks
#

source ~/.zshrc_local


#
# Finalize
#

# Fix slow pastes
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}

zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish

fpath=(~/.zsh $fpath)
autoload -Uz compinit && compinit

# Load iTerm integration
test -e /Users/aj/.iterm2_shell_integration.zsh && source /Users/aj/.iterm2_shell_integration.zsh || true
